### ISSUE TITLE
Invalid encoding UTF-8: defaulting to UTF-8.

### ISSUE THREAD

**Issue by codingbull** [pro-football-focus/docker-rscript#1]
Root cause of issue:
https://stackoverflow.com/questions/44143931/iconvlist-inconsistency-on-alpine-linux

@geofflane @iperks @chriserin Is there a way to get https://gitlab.alpinelinux.org/alpine/aports/-/commit/135fe81ec97aa27e819be7b6a6547820a85e8253 into our R builds? 
It will get rid of all of those Invalid encoding UTF-8: defaulting to UTF-8. warnings we see everywhere.

**Comment by geofflane** [comment]
I assume adding that sed line to the Dockerfile will fix that? Will try.

**Comment by codingbull** [comment]
It should, we ran it live when inside an image and it did fix the error messages

**Comment by geofflane** [comment]
Fixed in 4.0.5-2

**Comment by iperks** [comment]
AFAIK Greenline doesn't work for R version 4

**Comment by codingbull** [comment]
Well, it's there for the future then. And we've got it in the GL pipeline for the moment too.
Thanks all.

**Comment by geofflane** [comment]
In my defense no one mentioned Greenline or older versions. :)

**Comment by iperks** [comment]
perhaps we should have 2 branches?

**Comment by geofflane** [comment]
You can do a "hotfix" style branch off of the last 3.x build for sure and add the same change.

**Comment by iperks** [comment]
Is there much difference between the 3 and 4 from this perspective - there
didn't seem to be ...
